remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"
email: lesterguerzon@proton.me
description: >-
  Linux, cloud, Infrastructure-as-Code, and security ramblings or a recovering sysadmin. SRE wannabe.
baseurl: ""
url: "https://pidnull.io"
locale: "en-US"
title: "pidnull.io"
title_separator: "-"
search: true
twitter_username: pidnull
github_username: guerzon

# Build settings
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - jekyll-seo-tag

# Author
author:
  name: "Lester Guerzon"
  avatar: "/assets/images/pidnull-avatar.png"
  bio: "linux sysadmin who loves books, languages, and cycling. SRE wannabe."
  location: "Munich"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:lesterguerzon@proton.me"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/pidnull"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/guerzon"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/lesterguerzon"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      share: true
      related: true

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
