remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "dark"
description: >-
  k8s, cloud, golang, and security ramblings of a recovering sysadmin. SRE wannabe.
domain: guerzon.net
url: "https://guerzon.net"
repository: guerzon/guerzon.net
locale: "en-US"
title: "guerzon.net"
title_separator: "-"
search: true
twitter_username: guerzonix
github_username: guerzon

# Build settings
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-gist
  - jemoji
  - jekyll-seo-tag

# Author
author:
  name: "Lester Guerzon"
  avatar: "/assets/images/pidnull-avatar.png"
  bio: "k8s, cloud, golang, and security ramblings of a recovering sysadmin. SRE wannabe."
  location: "the interwebs"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/guerzon"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/guerzonlester/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:guerzon@proton.me"

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      share: true
      related: true

whitelist:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
